version: 2
updates:
  - package-ecosystem: "cargo"
    directory: "/"
    schedule:
      interval: "daily"
    ignore:
      # For AWS SDK for Rust, ignore all (but one) updates
      # - dependency-name: "aws-config"
      - dependency-name: "aws-endpoint"
      - dependency-name: "aws-http"
      - dependency-name: "aws-hyper"
      - dependency-name: "aws-sig*"
      - dependency-name: "aws-sdk*"
      - dependency-name: "aws-smithy*"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
