[package]
name = "tough-ssm"
version = "0.4.0"
description = "Implements AWS SSM as a key source for TUF signing keys"
authors = ["Zac Mrowicki <mrowicki@amazon.com>"]
license = "MIT OR Apache-2.0"
repository = "https://github.com/awslabs/tough"
keywords = ["TUF", "SSM"]
edition = "2018"

[features]
default = ["rusoto"]
rusoto = ["rusoto-rustls"]
rusoto-native-tls = ["rusoto_core/native-tls", "rusoto_credential", "rusoto_ssm/native-tls"]
rusoto-rustls = ["rusoto_core/rustls", "rusoto_credential", "rusoto_ssm/rustls"]

[dependencies]
tough = { version = "0.9.0", path = "../tough", features = ["http"] }
rusoto_core = { version = "0.45", optional = true, default-features = false }
rusoto_credential = { version = "0.45", optional = true }
rusoto_ssm = { version = "0.45", optional = true, default-features = false }
serde = "1.0.105"
serde_json = "1.0.59"
snafu = { version = "0.6.6", features = ["backtraces-impl-backtrace-crate"] }
tokio = "0.2.13"
