[package]
name = "tough"
version = "0.12.0"
description = "The Update Framework (TUF) repository client"
authors = ["iliana destroyer of worlds <iweller@amazon.com>"]
license = "MIT OR Apache-2.0"
repository = "https://github.com/awslabs/tough"
keywords = ["tuf", "update", "repository"]
edition = "2018"

[dependencies]
chrono = { version = "0.4.11", features = ["serde"] }
dyn-clone = "1.0.3"
globset = { version = "0.4.8" }
hex = "0.4.2"
log = "0.4.8"
olpc-cjson = { version = "0.1.0", path = "../olpc-cjson" }
path-absolutize = "3"
pem = "1.0.2"
percent-encoding = "2"
reqwest = { version = "0.11.1", optional = true, default-features = false, features = ["blocking"] }
ring = { version = "0.16.16", features = ["std"] }
serde = { version = "1.0.125", features = ["derive"] }
serde_json = "1.0.63"
serde_plain = "1.0.0"
snafu = "0.7"
tempfile = "3.1.0"
untrusted = "0.7.0"
url = "2.1.0"
walkdir = "2.3.2"

[dev-dependencies]
hex-literal = "0.3.4"
httptest = "0.15"
maplit = "1.0.1"

[features]
http = ["reqwest"]

# The `integ` feature enables integration tests. These tests require docker to be running on the host.
integ = []
