[package]
name = "tough"
version = "0.7.1"
description = "The Update Framework (TUF) repository client"
authors = ["iliana destroyer of worlds <iweller@amazon.com>"]
license = "MIT OR Apache-2.0"
repository = "https://github.com/awslabs/tough"
keywords = ["tuf", "update", "repository"]
edition = "2018"

[dependencies]
chrono = { version = "0.4.11", features = ["serde"] }
hex = "0.4.2"
olpc-cjson = { version = "0.1.0", path = "../olpc-cjson" }
pem = "0.7.0"
reqwest = { version = "0.10.4", optional = true, default-features = false, features = ["blocking"] }
ring = { version = "0.16.13", features = ["std"] }
serde = { version = "1.0.110", features = ["derive"] }
serde_json = "1.0.53"
serde_plain = "0.3.0"
snafu = "0.6.8"
untrusted = "0.7.0"
url = "2.1.0"
walkdir = "2.2.9"

[dev-dependencies]
hex-literal = "0.2.0"
tempfile = "3.1.0"
mockito = "0.25"

[features]
http = ["reqwest"]
